<a href="https://colab.research.google.com/github/ragingsilverback/Project-Euler/blob/master/Project_Euler(1-52).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Problem 1**


---


If we list all the natural numbers below 10 that are multiples of 3 or 5, we get 3, 5, 6 and 9. The sum of these multiples is 23.

Find the sum of all the multiples of 3 or 5 below 1000.

In [0]:
def func(number):
  a = []
  for i in range(1,number):
    if(i % 3 == 0):
      a.append(i)
    elif(i % 5 ==0):
      a.append(i)
  return sum(a)

a = 10
func(1000)

TypeError: ignored

**Problem 2**


---


Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

In [0]:
def fibonacci(number):
  if(number == 0 or number == 1):
    return 1
  else:
    return fibonacci(number - 1) + fibonacci(number - 2)

a = []
number = 1
while(fibonacci(number) < 4000000):
  if(fibonacci(number)%2 == 0):
    a.append(fibonacci(number))
  number += 1

print(sum(a))

4613732

**Problem 3**

---


The prime factors of 13195 are 5, 7, 13 and 29.

What is the largest prime factor of the number 600851475143 ?

In [0]:
import math

def primefact(number):
  a = []
  sqrt = int(math.sqrt(number))
  for i in range(2,sqrt):
    if(number % i == 0):
      flag = 0
      for j in range(2,i//2):
        if(i % j == 0):
          flag = 1
      if(flag == 0):
        a.append(i)
  return a[-1]

primefact(600851475143)

6857

**Problem 4**


---


A palindromic number reads the same both ways. The largest palindrome made from the product of two 2-digit numbers is 9009 = 91 Ã— 99.

Find the largest palindrome made from the product of two 3-digit numbers.

In [0]:
def palindrome():
  sol = []
  for i in range(100,1000):
    for j in range(100,1000):
      a = str(i*j)
      if(a == a[::-1]):
        sol.append(int(a))
  return sol

def largest(a):
  max = a[0]
  for i in a:
    if(i > max):
      max = i
  return max

largest(palindrome())

906609

**Problem 5**


---


2520 is the smallest number that can be divided by each of the numbers from 1 to 10 without any remainder.

What is the smallest positive number that is evenly divisible by all of the numbers from 1 to 20?

In [0]:
def smallest_10():
  number = 10
  buffer = 0
  while(buffer != 10):
    buffer = 0
    for i in range(1,11):
      if(number % i == 0):
        buffer = buffer + 1
    number = number + 10
  return number-10

def smallest_20():
  number = 20
  buffer = 0
  while(buffer != 20):
    buffer = 0
    for i in range(1,21):
      if(number % i == 0 ):
        buffer = buffer + 1
    number = number + 20
  return number-20


print(smallest_10())
smallest_20()

2520

232792560

**Problem 6**


---


The sum of the squares of the first ten natural numbers is,

12 + 22 + ... + 102 = 385
The square of the sum of the first ten natural numbers is,

(1 + 2 + ... + 10)2 = 552 = 3025
Hence the difference between the sum of the squares of the first ten natural numbers and the square of the sum is 3025 âˆ’ 385 = 2640.

Find the difference between the sum of the squares of the first one hundred natural numbers and the square of the sum.

In [0]:
def sum_of_squares(n):
  return n*(n+1)*(2*n+1)//6

def square_of_sum(n):
  return n*n*(n+1)*(n+1)//4

square_of_sum(100) - sum_of_squares(100)

25164150

**Problem 7**


---


By listing the first six prime numbers: 2, 3, 5, 7, 11, and 13, we can see that the 6th prime is 13.

What is the 10 001st prime number?

In [0]:
import math

def prime(n):
  a = 0
  primes = []
  number = 2
  while(a!=n):
    flag = 0
    sqrt  = int(math.sqrt(number)) + 1
    for i in range(2,sqrt):
      if(number % i == 0):
        flag = 1
    if(flag == 0):
      primes.append(number)
      a = a + 1
    number = number + 1
  return primes[-1]

prime(10001)

104743

**Problem 8**

---



The four adjacent digits in the 1000-digit number that have the greatest product are 9 Ã— 9 Ã— 8 Ã— 9 = 5832.

Find the thirteen adjacent digits in the 1000-digit number that have the greatest product. What is the value of this product?

In [0]:
a = str(7316717653133062491922511967442657474235534919493496983520312774506326239578318016984801869478851843858615607891129494954595017379583319528532088055111254069874715852386305071569329096329522744304355766896648950445244523161731856403098711121722383113622298934233803081353362766142828064444866452387493035890729629049156044077239071381051585930796086670172427121883998797908792274921901699720888093776657273330010533678812202354218097512545405947522435258490771167055601360483958644670632441572215539753697817977846174064955149290862569321978468622482839722413756570560574902614079729686524145351004748216637048440319989000889524345065854122758866688116427171479924442928230863465674813919123162824586178664583591245665294765456828489128831426076900422421902267105562632111110937054421750694165896040807198403850962455444362981230987879927244284909188845801561660979191338754992005240636899125607176060588611646710940507754100225698315520005593572972571636269561882670428252483600823257530420752963450)
largest = 0
sol = []
for i in range(0,len(a)-12):
  A = int(a[i])
  B = int(a[i+1])
  C = int(a[i+2])
  D = int(a[i+3])
  E = int(a[i+4])
  F = int(a[i+5])
  G = int(a[i+6])
  H = int(a[i+7])
  I = int(a[i+8])
  J = int(a[i+9])
  K = int(a[i+10])
  L = int(a[i+11])
  M = int(a[i+12])


  prod = A*B*C*D*E*F*G*H*I*J*K*L*M
  if(prod > largest):
    largest = prod
    sol.append([A,B,C,D,E,F,G,H,I,J,K,L,M])

print(largest)
print(sol[-1])

23514624000
[5, 5, 7, 6, 6, 8, 9, 6, 6, 4, 8, 9, 5]

**Problem 9**

---



A Pythagorean triplet is a set of three natural numbers, a < b < c, for which,

a2 + b2 = c2
For example, 32 + 42 = 9 + 16 = 25 = 52.

There exists exactly one Pythagorean triplet for which a + b + c = 1000.
Find the product abc.

In [0]:
def pythagorean_triplet(sum):
  sol = []
  for a in range(1,sum//2):
    for b in range(1,sum//2):
      for c in range(1,sum//2):
        if( a*a + b*b == c*c and a + b + c == sum):
          sol.append([a,b,c])
          
  return sol

pythagorean_triplet(1000)

[[200, 375, 425], [375, 200, 425]]

**Problem 10**

---



The sum of the primes below 10 is 2 + 3 + 5 + 7 = 17.

Find the sum of all the primes below two million.

In [0]:
import math

def sum_of_primes(total):
  number = 2
  sol = []
  while(number < total):
    sqrt = int(math.sqrt(number)) + 1
    flag = 0
    for i in range(2,sqrt):
      if(number % i == 0):
        flag = 1
    if(flag == 0):
      sol.append(number)
    number = number + 1     
  return sum(sol)

sum_of_primes(2000000)

142913828922

**Problem 11**


---


In the 20Ã—20 grid below, four numbers along a diagonal line have been marked in red.
The product of these numbers is 26 Ã— 63 Ã— 78 Ã— 14 = 1788696.

What is the greatest product of four adjacent numbers in the same direction (up, down, left, right, or diagonally) in the 20Ã—20 grid?

In [0]:
input = "08 02 22 97 38 15 00 40 00 75 04 05 07 78 52 12 50 77 91 08 49 49 99 40 17 81 18 57 60 87 17 40 98 43 69 48 04 56 62 00 81 49 31 73 55 79 14 29 93 71 40 67 53 88 30 03 49 13 36 65 52 70 95 23 04 60 11 42 69 24 68 56 01 32 56 71 37 02 36 91 22 31 16 71 51 67 63 89 41 92 36 54 22 40 40 28 66 33 13 80 24 47 32 60 99 03 45 02 44 75 33 53 78 36 84 20 35 17 12 50 32 98 81 28 64 23 67 10 26 38 40 67 59 54 70 66 18 38 64 70 67 26 20 68 02 62 12 20 95 63 94 39 63 08 40 91 66 49 94 21 24 55 58 05 66 73 99 26 97 17 78 78 96 83 14 88 34 89 63 72 21 36 23 09 75 00 76 44 20 45 35 14 00 61 33 97 34 31 33 95 78 17 53 28 22 75 31 67 15 94 03 80 04 62 16 14 09 53 56 92 16 39 05 42 96 35 31 47 55 58 88 24 00 17 54 24 36 29 85 57 86 56 00 48 35 71 89 07 05 44 44 37 44 60 21 58 51 54 17 58 19 80 81 68 05 94 47 69 28 73 92 13 86 52 17 77 04 89 55 40 04 52 08 83 97 35 99 16 07 97 57 32 16 26 26 79 33 27 98 66 88 36 68 87 57 62 20 72 03 46 33 67 46 55 12 32 63 93 53 69 04 42 16 73 38 25 39 11 24 94 72 18 08 46 29 32 40 62 76 36 20 69 36 41 72 30 23 88 34 62 99 69 82 67 59 85 74 04 36 16 20 73 35 29 78 31 90 01 74 31 49 71 48 86 81 16 23 57 05 54 01 70 54 71 83 51 54 69 16 92 33 48 61 43 52 01 89 19 67 48"
a = input.split(" ")
grid = []
for i in range(0,20):
  grid.append(a[i*20:i*20 + 20])

max_horizon = 0
sol_horizon = []
for i in range(0,20):
  for j in range(0,17):
    A = int(grid[i][j])
    B = int(grid[i][j+1])
    C = int(grid[i][j+2])
    D = int(grid[i][j+3])
    prod = A*B*C*D
    if(prod > max_horizon):
      max_horizon = prod
      sol_horizon.append([A,B,C,D,i,j])

max_vertical = 0
sol_vertical = []
for i in range(0,17):
  for j in range(0,20):
    A = int(grid[i][j])
    B = int(grid[i+1][j])
    C = int(grid[i+2][j])
    D = int(grid[i+3][j])
    prod = A*B*C*D
    if(prod > max_vertical):
      max_vertical = prod
      sol_vertical.append([A,B,C,D,i,j])

max_diag = 0
sol_diag = []
for i in range(0,17):
  for j in range(0,17):
    A = int(grid[i][j])
    B = int(grid[i+1][j+1])
    C = int(grid[i+2][j+2])
    D = int(grid[i+3][j+3])
    prod = A*B*C*D
    if(prod > max_diag):
      max_diag = prod
      sol_diag.append([A,B,C,D,i,j])

max_diag_b = 0
sol_diag_b = []
for i in range(0,17):
  for j in range(3,20):
    A = int(grid[i][j])
    B = int(grid[i+1][j-1])
    C = int(grid[i+2][j-2])
    D = int(grid[i+3][j-3])
    prod = A*B*C*D
    if(prod > max_diag_b):
      max_diag_b = prod
      sol_diag_b.append([A,B,C,D,i,j])

# print(max_horizon)
# print(sol_horizon[-1])
# print(max_vertical)
# print(sol_vertical[-1])
# print(max_diag)
# print(sol_diag[-1])
print(max(max_horizon,max_vertical,max_diag,max_diag_b))
print(sol_diag_b[-1])

70600674
[89, 94, 97, 87, 12, 6]

**Problem 12**


---


The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

 1: 1
 3: 1,3
 6: 1,2,3,6
10: 1,2,5,10
15: 1,3,5,15
21: 1,3,7,21
28: 1,2,4,7,14,28
We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?

In [0]:
import math

def triangle_number(n):
  return n*(n+1)//2

def factors(n):
  factors = 0
  sqrt  = int(math.sqrt(n))
  for i in range(1,sqrt):
    if(n%i == 0):
      factors += 2
  if(sqrt*sqrt == n):
    factors = factors - 1
  return factors

n = 1
while(factors(triangle_number(n)) < 500):
  n = n + 1

print(n)
triangle_number(n)

12375

76576500

**Problem 13**


---

Work out the first ten digits of the sum of the following one-hundred 50-digit numbers.

In [0]:
A = str(37107287533902102798797998220837590246510135740250463769376774900097126481248969700780504170182605387432498619952474105947423330951305812372661730962991942213363574161572522430563301811072406154908250230675882075393461711719803104210475137780632466768926167069662363382013637841838368417873436172675728112879812849979408065481931592621691275889832738442742289174325203219235894228767964876702721893184745144573600130643909116721685684458871160315327670386486105843025439939619828917593665686757934951621764571418565606295021572231965867550793241933316490635246274190492910143244581382266334794475817892575867718337217661963751590579239728245598838407582035653253593990084026335689488301894586282278288018119938482628201427819413994056758715117009439035398664372827112653829987240784473053190104293586865155060062958648615320752733719591914205172558297169388870771546649911559348760353292171497005693854370070576826684624621495650076471787294438377604532826541087568284431911906346940378552177792951453612327252500029607107508256381565671088525835072145876576172410976447339110607218265236877223636045174237069058518606604482076212098132878607339694128114266041808683061932846081119106155694051268969251934325451728388641918047049293215058642563049483624672216484350762017279180399446930047329563406911573244438690812579451408905770622942919710792820955037687525678773091862540744969844508330393682126183363848253301546861961243487676812975343759465158038628759287849020152168555482871720121925776695478182833757993103614740356856449095527097864797581167263201004368978425535399209318374414978068609844840309812907779179908821879532736447567559084803087086987551392711854517078544161852424320693150332599594068957565367821070749269665376763262354472106979395067965269474259770973916669376304263398708541052684708299085211399427365734116182760315001271653786073615010808570091499395125570281987460043753582903531743471732693212357815498262974255273730794953759765105305946966067683156574377167401875275889028025717332296191766687138199318110487701902712526768027607800301367868099252546340106163286652636270218540497705585629946580636237993140746255962240744869082311749777923654662572469233228109171419143028819710328859780666976089293863828502533340334413065578016127815921815005561868836468420090470230530811728164304876237919698424872550366387845831148769693215490281042402013833512446218144177347063783299490636259666498587618221225225512486764533677201869716985443124195724099139590089523100588229554825530026352078153229679624948164195386821877476085327132285723110424803456124867697064507995236377742425354112916842768655389262050249103265729672370191327572567528565324825826546309220705859652229798860272258331913126375147341994889534765745501184957014548792889848568277260777137214037988797153829820378303147352772158034814451349137322665138134829543829199918180278916522431027392251122869539409579530664052326325380441000596549391598795936352974615218550237130764225512118369380358038858490341698116222072977186158236678424689157993532961922624679571944012690438771072750481023908955235974572318970677254791506150550495392297953090112996751986188088225875314529584099251203829009407770775672113067397083047244838165338735023408456470580773088295917476714036319800818712901187549131054712658197623331044818386269515456334926366572897563400500428462801835170705278318394258821455212272512503275512160354698120058176216521282765275169129689778932238195734329339946437501907836945765883352399886755061649651847751807381688378610915273579297013376217784275219262340194239963916804498399317331273132924185707147349566916674687634660915035914677504995186714302352196288948901024233251169136196266227326746080059154747183079839286853520694694454072476841822524674417161514036427982273348055556214818971426179103425986472045168939894221798260880768528778364618279934631376775430780936333301898264209010848802521674670883215120185883543223812876952786713296124747824645386369930090493103636197638780396218407357239979422340623539380833965132740801111666627891981488087797941876876144230030984490851411606618262936828367647447792391803351109890697907148578694408955299065364044742557608365997664579509666024396409905389607120198219976047599490197230297649139826800329731560371200413779037855660850892521673093931987275027546890690370753941304265231501194809377245048795150954100921645863754710598436791786391670211874924319957006419179697775990283006991536871371193661495281130587638027841075444973307840789923115535562561142322423255033685442488917353448899115014406480203690680639606723221932041495354150312888033953605329934036800697771065056663195481234880673210146739058568557934581403627822703280826165707739483275922328459417065250945123252306082291880205877731971983945018088807242966198081119777158542502016545090413245809786882778948721859617721078384350691861554356628840622574736922845095162084960398013400172393067166682355524525280460972253503534226472524250874054075591789781264330331690)
C = []
for i in range(0,100):
  C.append(int(A[i*50:i*50 + 50]))

print(sum(C))

5537376230390876637302048746832985971773659831892672

**Problem 14**


---
The following iterative sequence is defined for the set of positive integers:

n â†’ n/2 (n is even)
n â†’ 3n + 1 (n is odd)

Using the rule above and starting with 13, we generate the following sequence:

13 â†’ 40 â†’ 20 â†’ 10 â†’ 5 â†’ 16 â†’ 8 â†’ 4 â†’ 2 â†’ 1
It can be seen that this sequence (starting at 13 and finishing at 1) contains 10 terms. Although it has not been proved yet (Collatz Problem), it is thought that all starting numbers finish at 1.

Which starting number, under one million, produces the longest chain?

In [0]:

def collatz(n):
  if(n % 2 == 0):
    return n//2
  else:
    return 3*n + 1

def collatz_seq(number):
  seq = []
  while(number!=1):
    seq.append(number)
    number = collatz(number)
  seq.append(1)
  return seq

max_len = 0
sol = []
for i in range(1,1000000):
  seq_len = len(collatz_seq(i))
  if( seq_len > max_len):
    max_len = seq_len
    sol.append(i)

print(max_len)
print(sol[-1])

525
837799

**Problem 15**


---
Starting in the top left corner of a 2Ã—2 grid, and only being able to move to the right and down, there are exactly 6 routes to the bottom right corner.


How many such routes are there through a 20Ã—20 grid?

In [0]:
# Solved through dynamic programming by matrix filling method
# Can Also be solved by Combinatorial Methods by just finding 40 C 20 i.e 2N C N

def grid_routes(n):
  sol = []
  for i in range(0,n):
    row = []
    for i in range(0,n):
      row.append(0)
    sol.append(row)
  for i in range(0,n-1):
    sol[n-1][i] = 1
    sol[i][n-1] = 1
  for i in range(n-2,-1,-1):
    for j in range(n-2,-1,-1):
      sol[i][j] = sol[i+1][j] + sol[i][j+1]
  return sol[0][0]

grid_routes(21)

137846528820

**Problem 16**


---
215 = 32768 and the sum of its digits is 3 + 2 + 7 + 6 + 8 = 26.

What is the sum of the digits of the number 21000?

In [0]:
import math
a = str(int(math.pow(2,1000)))
b = [int(a[i]) for i in range(0,len(a))]
print(sum(b))

1366

**Problem 17**


---

If the numbers 1 to 5 are written out in words: one, two, three, four, five, then there are 3 + 3 + 5 + 4 + 4 = 19 letters used in total.

If all the numbers from 1 to 1000 (one thousand) inclusive were written out in words, how many letters would be used?

In [0]:
# Bakchod Question , i am not solving it

**Problem 18**


---
By starting at the top of the triangle below and moving to adjacent numbers on the row below, the maximum total from top to bottom is 23.

3
7 4
2 4 6
8 5 9 3

That is, 3 + 7 + 4 + 9 = 23.

In [0]:
arr = [[3,0,0,0],[7,4,0,0],[2,4,6,0],[8,5,9,3]]

t = "75 0  0  0  0  0  0  0  0  0  0  0  0  0  0 95 64 0  0  0  0  0  0  0  0  0  0  0  0  0 17 47 82 0  0  0  0  0  0  0  0  0  0  0  0 18 35 87 10 0  0  0  0  0  0  0  0  0  0  0  20 04 82 47 65 0  0  0  0  0  0  0  0  0  0 19 01 23 75 03 34 0  0  0  0  0  0  0  0  0 88 02 77 73 07 63 67 0  0  0  0  0  0  0  0 99 65 04 28 06 16 70 92 0  0  0  0  0  0  0 41 41 26 56 83 40 80 70 33 0  0  0  0  0  0 41 48 72 33 47 32 37 16 94 29 0  0  0  0  0 53 71 44 65 25 43 91 52 97 51 14 0  0  0  0 70 11 33 28 77 73 17 78 39 68 17 57 0  0  0 91 71 52 38 17 14 91 43 58 50 27 29 48 0  0 63 66 04 68 89 53 67 30 73 16 69 87 40 31 0 04 62 98 27 23 09 70 98 73 93 38 53 60 04 23"
t = t.replace("  "," ")
t = t.split(" ")
A = []

for i in range(0,15):
  A.append(t[i*15:i*15 + 15])
  
# Solving This By Greedy Algorithm

def max_route(arr):
  sol = []
  top = arr[0][0]
  sol.append(top)
  for i in range(0,len(arr)-1):
    index = arr[i].index(top)
    top = max(arr[i+1][index:index+2])
    sol.append(top)
  return sol



# We can see that greeey algo doesn't give us the optimal solution

# let's try this by dynamic programming

def optimal_route(arr):
  result = arr
  for i in range(len(result)-2,0,-1):
    for j in range(0,len(result[i])):
      result[i][j] = int(result[i][j]) + int(max(result[i+1][j:j+2])) 
  
  return int(result[0][0]) + max(result[1])
  
  
optimal_route(A)

1074

**Problem 19**


---
You are given the following information, but you may prefer to do some research for yourself.

1 Jan 1900 was a Monday.
Thirty days has September,
April, June and November.
All the rest have thirty-one,
Saving February alone,
Which has twenty-eight, rain or shine.
And on leap years, twenty-nine.
A leap year occurs on any year evenly divisible by 4, but not on a century unless it is divisible by 400.
How many Sundays fell on the first of the month during the twentieth century (1 Jan 1901 to 31 Dec 2000)?

In [0]:
# Bakchod Question No. 2

**Problem 20**


---
n! means n Ã— (n âˆ’ 1) Ã— ... Ã— 3 Ã— 2 Ã— 1

For example, 10! = 10 Ã— 9 Ã— ... Ã— 3 Ã— 2 Ã— 1 = 3628800,
and the sum of the digits in the number 10! is 3 + 6 + 2 + 8 + 8 + 0 + 0 = 27.

Find the sum of the digits in the number 100!

In [0]:
import time

def factorial(n):
  product = 1
  for i in range(1,n+1):
    product = product*i
  return product

def combinatorics(n,c):
  nc = factorial(n)//(factorial(n-c)*factorial(c))
  return nc

start = time.time()

digit_seq = str(factorial(100))
lis = [int(digit_seq[i]) for i in range(0,len(digit_seq))]

end = time.time() - start
print(end)
print(sum(lis))

0.00013113021850585938
648

**Problem 21**


---
Let d(n) be defined as the sum of proper divisors of n (numbers less than n which divide evenly into n).
If d(a) = b and d(b) = a, where a â‰  b, then a and b are an amicable pair and each of a and b are called amicable numbers.

For example, the proper divisors of 220 are 1, 2, 4, 5, 10, 11, 20, 22, 44, 55 and 110; therefore d(220) = 284. The proper divisors of 284 are 1, 2, 4, 71 and 142; so d(284) = 220.

Evaluate the sum of all the amicable numbers under 10000.

In [0]:
import time
def d(n):
  divisors = []
  for i in range(1,n//2+1):
    if(n%i == 0):
      divisors.append(i)
  return sum(divisors)

start = time.time()


dic = {}
for i in range(1,10000):
  dic[i] = d(i)

sol = []
for i in range(1,10000):
  for j in range(1,10000):
    if(dic[i] == j and dic[j] == i and dic[i]!=i):
      sol.append(i)

end = time.time() - start
print(end)
print(sum(sol))

# Need to improve the solution,not the fastest around

13.029183149337769
31626

**Problem 22**


---

Using names.txt (right click and 'Save Link/Target As...'), a 46K text file containing over five-thousand first names, begin by sorting it into alphabetical order. Then working out the alphabetical value for each name, multiply this value by its alphabetical position in the list to obtain a name score.

For example, when the list is sorted into alphabetical order, COLIN, which is worth 3 + 15 + 12 + 9 + 14 = 53, is the 938th name in the list. So, COLIN would obtain a score of 938 Ã— 53 = 49714.

What is the total of all the name scores in the file?

In [0]:
name_file = open('/content/p022_names.txt')
names = []
for line in name_file:
  line = line.split(",")
  for i in range(0,len(line)):
    names.append(line[i].strip('"'))  

names.sort()

alpha_dic = {}
alphabets = ['A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z']

for i in range(0,len(alphabets)):
  alpha_dic[alphabets[i]] = i+1


def name_score(name,dic):
  score = 0
  for i in range(0,len(name)):
    score = score + dic[name[i]]
  return score

name_scores = []
for i in range(0,len(names)):
  score = name_score(names[i],alpha_dic)*(i+1)
  name_scores.append(score)


print(sum(name_scores))

871198282

**Problem 23**


---
A perfect number is a number for which the sum of its proper divisors is exactly equal to the number. For example, the sum of the proper divisors of 28 would be 1 + 2 + 4 + 7 + 14 = 28, which means that 28 is a perfect number.

A number n is called deficient if the sum of its proper divisors is less than n and it is called abundant if this sum exceeds n.

As 12 is the smallest abundant number, 1 + 2 + 3 + 4 + 6 = 16, the smallest number that can be written as the sum of two abundant numbers is 24. By mathematical analysis, it can be shown that all integers greater than 28123 can be written as the sum of two abundant numbers. However, this upper limit cannot be reduced any further by analysis even though it is known that the greatest number that cannot be expressed as the sum of two abundant numbers is less than this limit.

Find the sum of all the positive integers which cannot be written as the sum of two abundant numbers.

In [0]:
def abundant(n):
  div_sum = 0
  sol = []
  for i in range(1,n//2 + 1):
    if(n%i == 0):
      div_sum = div_sum + i
      sol.append(i)
  if(div_sum > n):
    return True
  else:
    return False


abundant_numbers = []
for i in range(2,28124):
  if(abundant(i)):
    abundant_numbers.append(i)

can_be_written_as_sum = [False]*28124


# Checkpoint 1
print("Checkpoint 1 Done")


for i in range(0,len(abundant_numbers)):
  if(i >= 28123//2):
    break
  for j in range(i,len(abundant_numbers)):
    if(abundant_numbers[i] + abundant_numbers[j] <= 28123):
      can_be_written_as_sum[abundant_numbers[i] + abundant_numbers[j]] = True
    else:
      break
# Checkpoint 2
print("Checkpoint 2 Done")


total = 0
for i in range(1,28124):
  if(can_be_written_as_sum[i] == False):
    total = total + i

print(total)

Checkpoint 1 Done
Checkpoint 2 Done
4179871

**Problem 24**


---
A permutation is an ordered arrangement of objects. For example, 3124 is one possible permutation of the digits 1, 2, 3 and 4. If all of the permutations are listed numerically or alphabetically, we call it lexicographic order. The lexicographic permutations of 0, 1 and 2 are:

012   021   102   120   201   210

What is the millionth lexicographic permutation of the digits 0, 1, 2, 3, 4, 5, 6, 7, 8 and 9?

In [0]:
def factorial(n):
  if(n == 1 or n == 0):
    return n
  else:
    return n*factorial(n-1)

def perm(s,n):
  a = []
  index = n-1
  i = 1
  duplicate = list(s) 
  while(len(a)!= len(s)+1):
    if(len(s)-i == 0):
      a.append(duplicate[-1])
      return a
    number = index//factorial(len(s)-i)
    new_index = index % factorial(len(s)-i)
    a.append(duplicate.pop(number))
    index = new_index
    i = i + 1
  return a

a = '0123456789'

perm(a,1000000)

['2', '7', '8', '3', '9', '1', '5', '4', '6', '0']

**Problem 25**


---
The Fibonacci sequence is defined by the recurrence relation:

Fn = Fnâˆ’1 + Fnâˆ’2, where F1 = 1 and F2 = 1.
Hence the first 12 terms will be:

F1 = 1
F2 = 1
F3 = 2
F4 = 3
F5 = 5
F6 = 8
F7 = 13
F8 = 21
F9 = 34
F10 = 55
F11 = 89
F12 = 144
The 12th term, F12, is the first term to contain three digits.

What is the index of the first term in the Fibonacci sequence to contain 1000 digits?

In [0]:
import time

def Fibonacci(n):
  if( n == 1 or n == 0):
    return n
  Fib = [0]*(n+1)
  Fib[0] = 0
  Fib[1] = 1
  for i in range(2,n+1):
    Fib[i] = Fib[i-1] + Fib[i-2]

  return Fib[n]

start = time.time()

n = 1
while(len(str(Fibonacci(n)))!= 1000):
  n = n + 1

print(n) 

end = time.time() - start

print(end)

# Pretty Fast i would say

4782
2.7436606884002686

**Problem 26**


---
A unit fraction contains 1 in the numerator. The decimal representation of the unit fractions with denominators 2 to 10 are given:

1/2	= 	0.5
1/3	= 	0.(3)
1/4	= 	0.25
1/5	= 	0.2
1/6	= 	0.1(6)
1/7	= 	0.(142857)
1/8	= 	0.125
1/9	= 	0.(1)
1/10	= 	0.1
Where 0.1(6) means 0.166666..., and has a 1-digit recurring cycle. It can be seen that 1/7 has a 6-digit recurring cycle.

Find the value of d < 1000 for which 1/d contains the longest recurring cycle in its decimal fraction part.

In [0]:
# a = 1
# n = 7

# found_remainders = []
# remainder = a % n
# while(remainder not in found_remainders):
#   found_remainders.append(remainder)
#   a = 10*remainder
#   remainder = a % 7

# print(found_remainders)

seq_length = 0
sol = []
for i in range(1000,1,-1):
  if(seq_length > i):
    break
  found_remainders = []
  a = 1
  remainder = a % i
  while(remainder not in found_remainders):
    found_remainders.append(remainder)
    a = 10*remainder
    remainder = a % i

  if(len(found_remainders) > seq_length):
    seq_length = len(found_remainders)
    sol.append(i)


print(sol[-1])
print(seq_length)

983
982

**Problem 27**


---
Euler discovered the remarkable quadratic formula:

n2+n+41
It turns out that the formula will produce 40 primes for the consecutive integer values 0â‰¤nâ‰¤39. However, when n=40,402+40+41=40(40+1)+41 is divisible by 41, and certainly when n=41,412+41+41 is clearly divisible by 41.

The incredible formula n2âˆ’79n+1601 was discovered, which produces 80 primes for the consecutive values 0â‰¤nâ‰¤79. The product of the coefficients, âˆ’79 and 1601, is âˆ’126479.

Considering quadratics of the form:

n2+an+b, where |a|<1000 and |b|â‰¤1000

where |n| is the modulus/absolute value of n
e.g. |11|=11 and |âˆ’4|=4
Find the product of the coefficients, a and b, for the quadratic expression that produces the maximum number of primes for consecutive values of n, starting with n=0.

In [0]:
from sympy import isprime
b_set = []
b_set.append(1)
for i in range(-1000,1001):
  if(isprime(i)):
    b_set.append(i)


a_max = 0
b_max = 0
n_max = 0

def quadratic(a,b,n):
  return(n*n + a*n + b)

for a in range(-999,1001,2):
  for b in b_set:
    n = 0
    while(isprime(qudratic(a,b,n))):
      n = n+1
    if(n > n_max):
      a_max = a
      b_max = b
      n_max = n

print(a_max,b_max,n_max)

-61 971 71

**Problem 28**


---
Starting with the number 1 and moving to the right in a clockwise direction a 5 by 5 spiral is formed as follows:

21 22 23 24 25
20  7  8  9 10
19  6  1  2 11
18  5  4  3 12
17 16 15 14 13

It can be verified that the sum of the numbers on the diagonals is 101.

What is the sum of the numbers on the diagonals in a 1001 by 1001 spiral formed in the same way?

In [0]:
# 21 22 23 24 25
# 20  7  8  9 10
# 19  6  1  2 11
# 18  5  4  3 12
# 17 16 15 14 13

# first_ring : n == 1 , ring_side length = 2n+1 , top_right_corner = (2n+1)*(2n+1)
# next corner moving counter clockwise = (2n+1)^2 - 2n
# next corner moving counter clockwise = (2n+1)^2 - 4n
# last corner = (2n+1)*2 - 6n
# total of all corners = (2n+1)^2 - 12n
# f(n) = (2n+1)^2 - 12n + f(n-1)

def diag_sum(n):
  if(n==0):
    return 1
  else:
    return 4*(2*n+1)*(2*n+1) - 12*n + diag_sum(n-1)

diag_sum(500)

669171001

**Problem 29**


---
Consider all integer combinations of ab for 2 â‰¤ a â‰¤ 5 and 2 â‰¤ b â‰¤ 5:

22=4, 23=8, 24=16, 25=32
32=9, 33=27, 34=81, 35=243
42=16, 43=64, 44=256, 45=1024
52=25, 53=125, 54=625, 55=3125
If they are then placed in numerical order, with any repeats removed, we get the following sequence of 15 distinct terms:

4, 8, 9, 16, 25, 27, 32, 64, 81, 125, 243, 256, 625, 1024, 3125

How many distinct terms are in the sequence generated by ab for 2 â‰¤ a â‰¤ 100 and 2 â‰¤ b â‰¤ 100?

In [0]:
from math import pow
lis = []
for a in range(2,101):
  for b in range(2,101):
    lis.append(int(pow(a,b)))

unique = []
for i in lis:
  if i not in unique:
    unique.append(i)

unique.sort()


print(len(unique))

9183

**Problem 30**


---
Surprisingly there are only three numbers that can be written as the sum of fourth powers of their digits:

1634 = 14 + 64 + 34 + 44
8208 = 84 + 24 + 04 + 84
9474 = 94 + 44 + 74 + 44
As 1 = 14 is not a sum it is not included.

The sum of these numbers is 1634 + 8208 + 9474 = 19316.

Find the sum of all the numbers that can be written as the sum of fifth powers of their digits.

In [0]:
from math import pow

def dig(n):
  s = str(n)
  sum_dig = 0
  for i in range(0,len(s)):
    sum_dig = sum_dig + pow(int(s[i]),5)
  if(sum_dig == n):
    return True
  else:
    return False

sol = []
for i in range(999,200000):
  if(dig(i)):
    sol.append(i)

print(sum(sol))

TypeError: ignored

**Problem 31**


---
In England the currency is made up of pound, Â£, and pence, p, and there are eight coins in general circulation:

1p, 2p, 5p, 10p, 20p, 50p, Â£1 (100p) and Â£2 (200p).
It is possible to make Â£2 in the following way:

1Ã—Â£1 + 1Ã—50p + 2Ã—20p + 1Ã—5p + 1Ã—2p + 3Ã—1p
How many different ways can Â£2 be made using any number of coins?

In [0]:
total = 200
coins = [1,2,5,10,20,50,100,200]
sol = [0]*201
sol[0] = 1

for i in range(0,len(coins)):
  for j in range(coins[i],201):
    sol[j] = sol[j] + sol[j - coins[i]]

print(sol)

# Not understood properly

[1, 1, 2, 2, 3, 4, 5, 6, 7, 8, 11, 12, 15, 16, 19, 22, 25, 28, 31, 34, 41, 44, 51, 54, 61, 68, 75, 82, 89, 96, 109, 116, 129, 136, 149, 162, 175, 188, 201, 214, 236, 249, 271, 284, 306, 328, 350, 372, 394, 416, 451, 473, 508, 530, 565, 600, 635, 670, 705, 740, 793, 828, 881, 916, 969, 1022, 1075, 1128, 1181, 1234, 1311, 1364, 1441, 1494, 1571, 1648, 1725, 1802, 1879, 1956, 2064, 2141, 2249, 2326, 2434, 2542, 2650, 2758, 2866, 2974, 3121, 3229, 3376, 3484, 3631, 3778, 3925, 4072, 4219, 4366, 4563, 4710, 4907, 5054, 5251, 5448, 5645, 5842, 6039, 6236, 6495, 6692, 6951, 7148, 7407, 7666, 7925, 8184, 8443, 8702, 9038, 9297, 9633, 9892, 10228, 10564, 10900, 11236, 11572, 11908, 12337, 12673, 13102, 13438, 13867, 14296, 14725, 15154, 15583, 16012, 16553, 16982, 17523, 17952, 18493, 19034, 19575, 20116, 20657, 21198, 21873, 22414, 23089, 23630, 24305, 24980, 25655, 26330, 27005, 27680, 28514, 29189, 30023, 30698, 31532, 32366, 33200, 34034, 34868, 35702, 36723, 37557, 38578, 39412, 40433, 41454, 42475, 43496, 44517, 45538, 46777, 47798, 49037, 50058, 51297, 52536, 53775, 55014, 56253, 57492, 58983, 60222, 61713, 62952, 64443, 65934, 67425, 68916, 70407, 71898, 73682]

**Problem 32**


---
We shall say that an n-digit number is pandigital if it makes use of all the digits 1 to n exactly once; for example, the 5-digit number, 15234, is 1 through 5 pandigital.

The product 7254 is unusual, as the identity, 39 Ã— 186 = 7254, containing multiplicand, multiplier, and product is 1 through 9 pandigital.

Find the sum of all products whose multiplicand/multiplier/product identity can be written as a 1 through 9 pandigital.

HINT: Some products can be obtained in more than one way so be sure to only include it once in your sum.

In [0]:
sol = []
for t in range(12,99):
  for v in range(123,988):
    product = t*v
    lis = []
    for a in str(t):
      lis.append(a)
    for b in str(v):
      lis.append(b)
    for c in str(product):
      lis.append(c)
    flag = 0
    for x in range(1,10):
      if(str(x) not in lis):
        flag = 1
    if(flag == 0):
      sol.append(product)

for t in range(1,10):
  for v in range(1234,9877):
    product = t*v
    lis = []
    for a in str(t):
      lis.append(a)
    for b in str(v):
      lis.append(b)
    for c in str(product):
      lis.append(c)
    flag = 0
    for x in range(1,10):
      if(str(x) not in lis):
        flag = 1
    if(flag == 0):
      sol.append(product)


unique_sol = []
for products in sol:
  if(products not in unique_sol):
    unique_sol.append(products)

final_sols = []
for sols in unique_sol:
  if(len(str(sols)) < 5):
    final_sols.append(sols)

print(sum(final_sols))

45228

**Problem 33**


---
The fraction 49/98 is a curious fraction, as an inexperienced mathematician in attempting to simplify it may incorrectly believe that 49/98 = 4/8, which is correct, is obtained by cancelling the 9s.

We shall consider fractions like, 30/50 = 3/5, to be trivial examples.

There are exactly four non-trivial examples of this type of fraction, less than one in value, and containing two digits in the numerator and denominator.

If the product of these four fractions is given in its lowest common terms, find the value of the denominator.

In [0]:
def trivial_frac(a,b):
  if(a==b):
    return
  elif(a%10 ==0 and b%10 ==0):
    return
  num = a/b
  a_str = str(a)
  b_str = str(b)
  key_a = 0
  key_b = 0
  for i in range(0,len(a_str)):
    for j in range(0,len(b_str)):
      if(a_str[i]==b_str[j]):
        key_a = i
        key_b = j
  if(key_a > 0):
    a_str = a_str[0:key_a] + a_str[key_a+1:]
    b_str = b_str[0:key_b] + b_str[key_b+1:]
  if(int(b_str)==0):
    new_number = 0
  else:
    new_number = int(a_str)/int(b_str)
  if(num == new_number and key_a > 0):
    return True
  else:
    return False


non_trivials = []
for i in range(11,99):
  for j in range(i,99):
    if(trivial_frac(i,j)==True):
      non_trivials.append([i,j])

print(non_trivials)

def largest_fac(a,b):
  largest = 1
  for i in range(2,a+1):
    if(a%i==0 and b%i==0):
      if(i > largest):
        largest = i
  return largest

product_n = 1
product_d = 1

for i in non_trivials:
  num,denom = i
  denom = denom/largest_fac(num,denom)
  # num = num/largest_fac(num,denom)
  # product_n = num*product_n
  product_d = denom*product_d

print(product_n,product_d)

[[16, 64], [19, 95], [26, 65], [49, 98]]
1 200.0

**Problem 34**


---
145 is a curious number, as 1! + 4! + 5! = 1 + 24 + 120 = 145.

Find the sum of all numbers which are equal to the sum of the factorial of their digits.

Note: as 1! = 1 and 2! = 2 are not sums they are not included.

In [0]:
def factorial(n):
  if(n == 1 or n == 0):
    return 1
  else:
    return n*factorial(n-1)

def curious(n):
  n_str = str(n)
  a = sum([factorial(int(n_str[i])) for i in range(0,len(n_str))])
  if(a == n):
    return True
  else:
    return False

sol = []

for i in range(3,100000):
  if(curious(i)):
    sol.append(i)

print(sum(sol))

40730

**Problem 35**


---
The number, 197, is called a circular prime because all rotations of the digits: 197, 971, and 719, are themselves prime.

There are thirteen such primes below 100: 2, 3, 5, 7, 11, 13, 17, 31, 37, 71, 73, 79, and 97.

How many circular primes are there below one million?

In [0]:
from sympy import isprime
from itertools import permutations



def int_perms(n):
  a = permutations(list(str(n)))
  sol = []
  for numbers in a:
    num = ""
    for i in numbers:
      num = num + i
    sol.append(int(num))
  return sol


sol = []  
for i in range(2,1000000):
  if(isprime(i)==True):
    a = int_perms(i)
    flag = True
    for j in a:
      if(isprime(j)==False):
        flag = False
    if(flag==True):
      sol.append(i)


print(len(sol))

#  Very Slow, need to optimize

KeyboardInterrupt: ignored

**Problem 36**


---
The decimal number, 585 = 10010010012 (binary), is palindromic in both bases.

Find the sum of all numbers, less than one million, which are palindromic in base 10 and base 2.

(Please note that the palindromic number, in either base, may not include leading zeros.)

In [0]:
def palindrome_10(n):
  n_str = str(n)
  if(n_str == n_str[::-1]):
    return True
  else:
    return False

def palindrome_2(n):
  a = str(bin(n).replace("0b",""))
  if(a == a[::-1]):
    return True
  else:
    return False

sol = []

for i in range(1,1000000):
  if(palindrome_10(i)==True and palindrome_2(i)==True):
    sol.append(i)

print(sum(sol))

872187

**Problem 37**


---
The number 3797 has an interesting property. Being prime itself, it is possible to continuously remove digits from left to right, and remain prime at each stage: 3797, 797, 97, and 7. Similarly we can work from right to left: 3797, 379, 37, and 3.

Find the sum of the only eleven primes that are both truncatable from left to right and right to left.

NOTE: 2, 3, 5, and 7 are not considered to be truncatable primes.

In [0]:
from sympy import isprime

primes = [False]*1000000

for i in range(1,1000001):
  if(isprime(i)==True):
    primes[i] = True

def truncs(n):
  n_str = str(n)
  sol = []
  for i in range(0,len(n_str)):
    a = n_str[:i+1]
    b = n_str[-(i+1):]
    sol.append(int(b))
    sol.append(int(a))

  return sol

sol = []
for i in range(11,1000000):
  if(len(sol)==11):
    break;
  if(primes[i]==True):
    Flag = True
    a = truncs(i)
    for j in a:
      if(primes[j]==False):
        Flag = False
        break;
    if(Flag==True):
      sol.append(i)

print(sum(sol))

748317

**Problem 38**


---
Take the number 192 and multiply it by each of 1, 2, and 3:

192 Ã— 1 = 192
192 Ã— 2 = 384
192 Ã— 3 = 576
By concatenating each product we get the 1 to 9 pandigital, 192384576. We will call 192384576 the concatenated product of 192 and (1,2,3)

The same can be achieved by starting with 9 and multiplying by 1, 2, 3, 4, and 5, giving the pandigital, 918273645, which is the concatenated product of 9 and (1,2,3,4,5).

What is the largest 1 to 9 pandigital 9-digit number that can be formed as the concatenated product of an integer with (1,2, ... , n) where n > 1?

In [0]:
def pandigital(num,m):
  s = ""
  for i in range(1,m+1):
    s = s + str(num*i)
  if(len(s)==9 and s[0]!=s[1] and s[1]!=s[2] and s[2]!=s[3] and s[3]!=s[4] and s[4]!=s[5] and s[5]!=s[6] and s[6]!=s[7] and s[7]!=s[8]):
    return int(s)
  else:
    return 0

largest = 0
for i in range(2,9):
  for num in range(9123,9876):
    if(pandigital(num,i) > largest):
      largest = pandigital(num,i)

print(largest)

987519750

**Problem 39**


---
If p is the perimeter of a right angle triangle with integral length sides, {a,b,c}, there are exactly three solutions for p = 120.

{20,48,52}, {24,45,51}, {30,40,50}

For which value of p â‰¤ 1000, is the number of solutions maximised?

In [0]:
largest = 0
result = 0
for p in range(2,1001,2):
  num_sol = 0
  for a in range(2,p//3,1):
    if(p*(p-2*a)%(2*(p-a))==0):
        num_sol = num_sol + 1
    # for b in range(2,p//2):
    #   if(a*a  + b*b == (p-a-b)*(p-a-b)):
        # num_sol = num_sol + 1
  if(num_sol > largest):
    largest = num_sol
    result = p

print(result)
print(largest)

840
9

**Problem 40**


---
An irrational decimal fraction is created by concatenating the positive integers:

0.123456789101112131415161718192021...

It can be seen that the 12th digit of the fractional part is 1.

If dn represents the nth digit of the fractional part, find the value of the following expression.

d1 Ã— d10 Ã— d100 Ã— d1000 Ã— d10000 Ã— d100000 Ã— d1000000

In [0]:
a = ""
for i in range(1,1000001):
  a = a + str(i)

indexes = [0,9,99,999,9999,99999,999999]
prod = 1
for index in indexes:
  prod = prod*int(a[index])

print(prod)

210

**Problem 41**


---
We shall say that an n-digit number is pandigital if it makes use of all the digits 1 to n exactly once. For example, 2143 is a 4-digit pandigital and is also prime.

What is the largest n-digit pandigital prime that exists?

In [0]:
from sympy import isprime

def pandigital(n):
  n_str = str(n)
  flag = True
  for i in range(1,len(n_str)+1):
    if str(i) not in n_str:
      flag = False
  if(flag == True):
    return True
  else:
    return False


# primes = []
# for i in range(1000000,7654321):
#   if(isprime(i)==True):
#     primes.append(i)

# result = 0
# primes_rev = primes[::-1]

# for prime in primes_rev:
#   if(pandigital(prime)==True):
#     result = prime
#     break;
result = 0
for i in range(7654321,1000000,-1):
  if(pandigital(i)==True and isprime(i)==True):
    result = i
    break;
    
    



print(result)

7652413

**Problem 42**


---
The nth term of the sequence of triangle numbers is given by, tn = Â½n(n+1); so the first ten triangle numbers are:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

By converting each letter in a word to a number corresponding to its alphabetical position and adding these values we form a word value. For example, the word value for SKY is 19 + 11 + 25 = 55 = t10. If the word value is a triangle number then we shall call the word a triangle word.

Using words.txt (right click and 'Save Link/Target As...'), a 16K text file containing nearly two-thousand common English words, how many are triangle words?

In [0]:
f = open('/content/p042_words.txt')
words = []
for line in f:
  line = line.split(',')
  for word in line:
    words.append(word.strip('"'))

alpha_dic = {}
alphabets = ['A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z']

for i in range(0,len(alphabets)):
  alpha_dic[alphabets[i]] = i+1

scores = []
for word in words:
  score = 0
  for i in word:
    score = score + alpha_dic[i]
  scores.append(score)

scores_copy = scores
scores_copy.sort()
largest = scores_copy[-1]

triangle_nums= []
for i in range(1,21):
  triangle_nums.append(i*(i+1)//2)

t_words = 0
for score in scores:
  if score in triangle_nums:
    t_words = t_words + 1

print(t_words)

162

**Problem 44**


---
Pentagonal numbers are generated by the formula, Pn=n(3nâˆ’1)/2. The first ten pentagonal numbers are:

1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...

It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference, 70 âˆ’ 22 = 48, is not pentagonal.

Find the pair of pentagonal numbers, Pj and Pk, for which their sum and difference are pentagonal and D = |Pk âˆ’ Pj| is minimised; what is the value of D?

In [0]:
from math import sqrt

def ispentagon(x):
  numm = 1 + sqrt(1+24*x)
  if(numm%6==0):
    return True
  else:
    return False

pentagon = [0]*5000
for i in range(1,5001):
  pentagon[i-1] = i*(3*i-1)//2

minn = 10000000
sol = []
for j in range(0,len(pentagon)-1):
  for k in range(j+1,len(pentagon)):
    diff = pentagon[k] - pentagon[j]
    summ = pentagon[k] + pentagon[j]
    if(ispentagon(diff)==True and ispentagon(summ)==True):
      if(diff < minn):
        minn = diff
        sol.append([k+1,j+1])

      
print("The Value of k and j are ",sol[-1])
print(minn)

The Value of k and j are  [2167, 1020]
5482660

**Problem 45**


---
Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:

Triangle	 	Tn=n(n+1)/2	 	1, 3, 6, 10, 15, ...
Pentagonal	 	Pn=n(3nâˆ’1)/2	 	1, 5, 12, 22, 35, ...
Hexagonal	 	Hn=n(2nâˆ’1)	 	1, 6, 15, 28, 45, ...
It can be verified that T285 = P165 = H143 = 40755.

Find the next triangle number that is also pentagonal and hexagonal.

In [0]:
from math import sqrt
def ispentagon(x):
  numm = 1 + sqrt(1+24*x)
  if(numm%6==0):
    return True
  else:
    return False

def ishexagonal(x):
  numm = 1 + sqrt(1+8*x)
  if(numm%4==0):
    return True
  else:
    return False

triangle_numms = [0]*1000000
for i in range(1,len(triangle_numms)+1):
  triangle_numms[i-1] = i*(i+1)//2

count = 0
for num in triangle_numms:
  if(count == 3):
    break
  if(ispentagon(num)==True and ishexagonal(num)==True):
    print(num)
    count = count + 1

1
40755
1533776805

**Problem 46**


---
It was proposed by Christian Goldbach that every odd composite number can be written as the sum of a prime and twice a square.

9 = 7 + 2Ã—12
15 = 7 + 2Ã—22
21 = 3 + 2Ã—32
25 = 7 + 2Ã—32
27 = 19 + 2Ã—22
33 = 31 + 2Ã—12

It turns out that the conjecture was false.

What is the smallest odd composite that cannot be written as the sum of a prime and twice a square?

In [0]:
from sympy import isprime

odd_composites = []
for i in range(2,10000):
  if(i%2==1 and isprime(i)==False):
    odd_composites.append(i)

primes = []
for i in range(1,10000):
  if(isprime(i)==True):
    primes.append(i)

square_roots = [i*i for i in range(0,100)]

def goldbcomposite(n,p):
  Flag = False
  for i in p:
    if(i > n):
      break
    numm = (n - i)/2
    # print(numm)
    if(numm in square_roots):
      Flag = True
      break
    else:
      Flag = False
    
  if(Flag==True):
    return True
  else:
    return False

for num in odd_composites:
  if(goldbcomposite(num,primes)==False):
    print(num)
    break

True
5777

**Problem 47**


---
he first two consecutive numbers to have two distinct prime factors are:

14 = 2 Ã— 7
15 = 3 Ã— 5

The first three consecutive numbers to have three distinct prime factors are:

644 = 2Â² Ã— 7 Ã— 23
645 = 3 Ã— 5 Ã— 43
646 = 2 Ã— 17 Ã— 19.

Find the first four consecutive integers to have four distinct prime factors each. What is the first of these numbers?

In [0]:
from sympy import isprime
primes = []

for i in range(2,200000):
  if(isprime(i)==True):
    primes.append(i)

def prime_factors(n,p):
  sol = []
  for i in p:
    if(i > n//2):
      break
    if(n%i==0):
      sol.append(i)
  return sol


for i in range(100000,200000):
  if(len(prime_factors(i,primes))==4 and len(prime_factors(i+1,primes))==4 and len(prime_factors(i+2,primes))==4 and len(prime_factors(i+3,primes))==4):
    print(i,i+1,i+2,i+3)
    break

134043 134044 134045 134046

**Problem 48**


---
The series, 11 + 22 + 33 + ... + 1010 = 10405071317.

Find the last ten digits of the series, 11 + 22 + 33 + ... + 10001000.

In [0]:
from math import pow
n = 1000
result = 0
for i in range(1,101):
  result = result + pow(i,i)

print(result)


# Not Done

1.0037111574617645e+200

**Problem 49**


---
The arithmetic sequence, 1487, 4817, 8147, in which each of the terms increases by 3330, is unusual in two ways: (i) each of the three terms are prime, and, (ii) each of the 4-digit numbers are permutations of one another.

There are no arithmetic sequences made up of three 1-, 2-, or 3-digit primes, exhibiting this property, but there is one other 4-digit increasing sequence.

What 12-digit number do you form by concatenating the three terms in this sequence?

In [0]:
from itertools import permutations
from sympy import isprime

def pintperms(n):
  perms = list(permutations(str(n)))
  sol = []
  for sets in perms:
    num = ''
    for i in sets:
      num = num + i
    sol.append(int(num))
  prime_perms = []
  a = 0
  for i in sol:
    if(isprime(i)==True and i > a ):
      prime_perms.append(i)
      a = i
  return prime_perms


for num in range(1000,10000):
  if(isprime(num)==True):
    test = pintperms(num)
    for i in range(0,len(test)-1):
      for j in range(i+1,len(test)):
        k = test[j] + test[j] - test[i]
        if(k in test):
          print([test[i],test[j],k])
          break
  else:
    pass

[1487, 4817, 8147]
[2969, 6299, 9629]

**Problem 50**


---
he prime 41, can be written as the sum of six consecutive primes:

41 = 2 + 3 + 5 + 7 + 11 + 13
This is the longest sum of consecutive primes that adds to a prime below one-hundred.

The longest sum of consecutive primes below one-thousand that adds to a prime, contains 21 terms, and is equal to 953.

Which prime, below one-million, can be written as the sum of the most consecutive primes?

In [0]:
from sympy import isprime
primes = []
for i in range(0,1000000):
  if(isprime(i)==True):
    primes.append(i)

max_sum = 0
maxlen = -1

for i in range(0,len(primes)):
  summ = 0
  for j in range(i,len(primes)):
    summ = summ + primes[j]
    if(summ > 1000000):
      break
    if(isprime(summ)==True and summ > max_sum and j-i > maxlen):
      maxlen = j - i +1
      max_sum = summ

print(max_sum)
print(maxlen)

997651
543

**Problem 52**


---
It can be seen that the number, 125874, and its double, 251748, contain exactly the same digits, but in a different order.

Find the smallest positive integer, x, such that 2x, 3x, 4x, 5x, and 6x, contain the same digits.

In [0]:
from itertools import permutations

def perms(n):
  a = list(permutations(str(n)))
  sol = []
  for sets in a:
    num = ''
    for i in sets:
      num = num + i
    sol.append(int(num))
  return sol

i = 123456
while(True):
  t = perms(i)
  j = 2*i
  k = 3*i
  l = 4*i
  m = 5*i
  n = 6*i
  if(i in t and j in t and k in t and l in t and m in t and n in t):
    print(i)
    break
  i = i + 3

142857